(() => {
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  let components=[{id:1,type:"cell",x:10,y:45,value:9},{id:2,type:"resistor",x:42,y:25,value:10},{id:3,type:"resistor",x:42,y:66,value:15}];
  let layout="series",nextId=4,selected=2;
  const types={
    cell:{label:"Cell",symbol:"ε",unit:"V",value:9},resistor:{label:"Resistor",symbol:"R",unit:"Ω",value:10},lamp:{label:"Lamp",symbol:"💡",unit:"Ω",value:12},diode:{label:"Diode",symbol:"▶|",unit:"Ω",value:5},ntc:{label:"NTC",symbol:"NTC",unit:"Ω",value:8},ldr:{label:"LDR",symbol:"LDR",unit:"Ω",value:10}
  };
  function inject(){const root=$("#labPlus");if(!root||$("#circuitSandbox"))return;const s=document.createElement("section");s.id="circuitSandbox";s.className="labplus-panel circuit-sandbox";s.innerHTML=`
    <div class="sandbox-head"><div><span class="eyebrow">Circuit Sandbox</span><h3>Build, move and inspect your own circuit</h3><p class="labplus-note">Drag components around the board, switch series/parallel layout, then select a component to inspect its current and p.d.</p></div><div class="sandbox-layout-switch"><button class="button primary" data-sb-layout="series">Series</button><button class="button" data-sb-layout="parallel">Parallel</button></div></div>
    <div class="sandbox-grid"><div><div class="sandbox-palette">${Object.entries(types).map(([k,v])=>`<button class="sandbox-add" data-sb-add="${k}"><strong>${v.symbol}</strong><span>${v.label}</span></button>`).join("")}</div><div class="sandbox-board" id="sandboxBoard"><svg class="sandbox-wires" id="sandboxWires"></svg><div class="sandbox-empty">Drag components to rearrange the circuit</div></div></div><aside class="sandbox-side"><div class="labplus-card"><h4>Selected component</h4><div id="sandboxInspector"></div></div><div class="labplus-card"><h4>Circuit calculation</h4><div id="sandboxSummary"></div></div><div class="labplus-actions"><button class="button" id="sandboxDelete">Delete selected</button><button class="button" id="sandboxReset">Reset sandbox</button></div></aside></div>`;root.insertAdjacentElement("afterend",s);render();bind();}
  function circuit(){const cell=components.find(c=>c.type==="cell")||{value:0};const rs=components.filter(c=>c.type!=="cell");let R=0;if(!rs.length)R=Infinity;else if(layout==="series")R=rs.reduce((a,c)=>a+c.value,0);else R=1/rs.reduce((a,c)=>a+1/c.value,0);const I=Number.isFinite(R)&&R>0?cell.value/R:0;return {V:cell.value,R,I,rs};}
  function compReading(c){const q=circuit();if(c.type==="cell")return {I:q.I,V:q.V,R:0};if(layout==="series")return {I:q.I,V:q.I*c.value,R:c.value};return {I:q.V/c.value,V:q.V,R:c.value};}
  function wires(){const svg=$("#sandboxWires"),board=$("#sandboxBoard");if(!svg||!board)return;const w=board.clientWidth,h=board.clientHeight;svg.setAttribute("viewBox",`0 0 ${w} ${h}`);const pts=components.map(c=>({c,x:c.x/100*w+42,y:c.y/100*h+30}));let lines="";if(layout==="series"&&pts.length>1){const sorted=[...pts].sort((a,b)=>a.x-b.x);for(let i=0;i<sorted.length-1;i++)lines+=`<path d="M${sorted[i].x} ${sorted[i].y} L${sorted[i+1].x} ${sorted[i+1].y}"/>`;lines+=`<path d="M${sorted[0].x} ${sorted[0].y} L${sorted[0].x} ${h-18} L${sorted.at(-1).x} ${h-18} L${sorted.at(-1).x} ${sorted.at(-1).y}"/>`;}else if(layout==="parallel"&&pts.length){const cell=pts.find(p=>p.c.type==="cell"),branches=pts.filter(p=>p.c.type!=="cell");if(cell){const top=38,bottom=h-35;lines+=`<path d="M${cell.x} ${cell.y} L${cell.x} ${top} L${w-45} ${top} M${cell.x} ${cell.y} L${cell.x} ${bottom} L${w-45} ${bottom}"/>`;for(const p of branches)lines+=`<path d="M${p.x} ${top} L${p.x} ${p.y-30} M${p.x} ${p.y+30} L${p.x} ${bottom}"/>`;}}svg.innerHTML=lines;}
  function render(){const b=$("#sandboxBoard");if(!b)return;b.querySelectorAll(".sandbox-component").forEach(x=>x.remove());for(const c of components){const t=types[c.type],el=document.createElement("button");el.className=`sandbox-component ${selected===c.id?"selected":""}`;el.dataset.sbId=c.id;el.style.left=c.x+"%";el.style.top=c.y+"%";el.innerHTML=`<strong>${t.symbol}</strong><span>${t.label}</span><small>${c.value} ${t.unit}</small>`;b.appendChild(el);}wires();renderInspector();}
  function renderInspector(){const c=components.find(x=>x.id===selected),q=circuit();if(c){const r=compReading(c),t=types[c.type];$("#sandboxInspector").innerHTML=`<p><strong>${t.label}</strong></p><label class="labplus-mini">Component value<input id="sandboxValue" type="number" step="0.1" value="${c.value}"></label><div class="reading-strip"><div><strong>${r.I.toFixed(3)} A</strong><span>current</span></div><div><strong>${r.V.toFixed(3)} V</strong><span>p.d.</span></div><div><strong>${r.R.toFixed(2)} Ω</strong><span>resistance</span></div></div>`;}else $("#sandboxInspector").innerHTML="<p class='labplus-note'>Select a component.</p>";$("#sandboxSummary").innerHTML=`<p><strong>${layout==="series"?"Series":"Parallel"} network</strong></p><p>Total resistance: <strong>${Number.isFinite(q.R)?q.R.toFixed(3):"—"} Ω</strong></p><p>Supply: <strong>${q.V.toFixed(2)} V</strong></p><p>Total current: <strong>${q.I.toFixed(3)} A</strong></p><p class="labplus-mini">The sandbox uses idealised component resistance values so students can focus on circuit structure and conservation laws.</p>`;$$('[data-sb-layout]').forEach(x=>x.classList.toggle("primary",x.dataset.sbLayout===layout));}
  function bindDrag(el){const board=$("#sandboxBoard"),id=Number(el.dataset.sbId);let down=false;const move=e=>{if(!down)return;const r=board.getBoundingClientRect(),c=components.find(x=>x.id===id);if(!c)return;c.x=Math.max(1,Math.min(88,(e.clientX-r.left)/r.width*100));c.y=Math.max(8,Math.min(80,(e.clientY-r.top)/r.height*100));el.style.left=c.x+"%";el.style.top=c.y+"%";wires();};el.addEventListener("pointerdown",e=>{down=true;selected=id;$$('.sandbox-component').forEach(x=>x.classList.toggle('selected',Number(x.dataset.sbId)===id));renderInspector();el.setPointerCapture?.(e.pointerId);});el.addEventListener("pointermove",move);el.addEventListener("pointerup",()=>{down=false;renderInspector();});el.addEventListener("pointercancel",()=>down=false);}
  function bind(){document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.sbAdd){const t=types[b.dataset.sbAdd];components.push({id:nextId++,type:b.dataset.sbAdd,x:25+Math.random()*50,y:20+Math.random()*55,value:t.value});selected=components.at(-1).id;render();return;}if(b.dataset.sbLayout){layout=b.dataset.sbLayout;render();return;}if(b.dataset.sbId){selected=Number(b.dataset.sbId);renderInspector();$$('.sandbox-component').forEach(x=>x.classList.toggle('selected',Number(x.dataset.sbId)===selected));return;}if(b.id==="sandboxDelete"){components=components.filter(c=>c.id!==selected);selected=components[0]?.id||null;render();return;}if(b.id==="sandboxReset"){components=[{id:1,type:"cell",x:10,y:45,value:9},{id:2,type:"resistor",x:42,y:25,value:10},{id:3,type:"resistor",x:42,y:66,value:15}];layout="series";nextId=4;selected=2;render();return;}});document.addEventListener("change",e=>{if(e.target.id==="sandboxValue"){const c=components.find(x=>x.id===selected);if(c){c.value=Math.max(.1,Number(e.target.value)||.1);render();}}});const obs=new MutationObserver(()=>{$$(".sandbox-component").forEach(el=>{if(!el.dataset.dragBound){el.dataset.dragBound="1";bindDrag(el);}});});obs.observe($("#sandboxBoard"),{childList:true});$$('.sandbox-component').forEach(el=>{el.dataset.dragBound="1";bindDrag(el);});window.addEventListener("resize",wires);}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",inject);else inject();
})();