(() => {
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  let components=[{id:1,type:"cell",x:10,y:45,value:9},{id:2,type:"resistor",x:42,y:25,value:10},{id:3,type:"resistor",x:42,y:66,value:15}];
  let layout="series",nextId=4,selected=2;
  const types={
    cell:{label:"Cell",symbol:"ε",unit:"V",value:9},resistor:{label:"Resistor",symbol:"R",unit:"Ω",value:10},lamp:{label:"Lamp",symbol:"💡",unit:"Ω",value:12},diode:{label:"Diode",symbol:"▶|",unit:"Ω",value:5},ntc:{label:"NTC",symbol:"NTC",unit:"Ω",value:8},ldr:{label:"LDR",symbol:"LDR",unit:"Ω",value:10}
  };
  function inject(){const root=$("#labPlus");if(!root||$("#circuitSandbox"))return;const s=document.createElement("section");s.id="circuitSandbox";s.className="labplus-panel circuit-sandbox";s.innerHTML=`
    <div class="sandbox-head"><div><span class="eyebrow">Circuit Sandbox</span><h3>Build, move and inspect your own circuit</h3><p class="labplus-note">Drag components, switch between series and parallel, and inspect current and p.d.</p></div><div class="sandbox-layout-switch"><button class="button primary" data-sb-layout="series">Series</button><button class="button" data-sb-layout="parallel">Parallel</button></div></div>
    <div class="sandbox-grid"><div><div class="sandbox-palette">${Object.entries(types).map(([k,v])=>`<button class="sandbox-add" data-sb-add="${k}"><strong>${v.symbol}</strong><span>${v.label}</span></button>`).join("")}</div><div class="sandbox-board" id="sandboxBoard"><svg class="sandbox-wires" id="sandboxWires"></svg><div class="sandbox-empty">Drag components to rearrange the circuit</div></div></div><aside class="sandbox-side"><div class="labplus-card"><h4>Selected component</h4><div id="sandboxInspector"></div></div><div class="labplus-card"><h4>Circuit calculation</h4><div id="sandboxSummary"></div></div><div class="labplus-actions"><button class="button" id="sandboxDelete">Delete selected</button><button class="button" id="sandboxReset">Reset sandbox</button></div></aside></div>`;root.insertAdjacentElement("afterend",s);render();bind();}
  function circuit(){const cell=components.find(c=>c.type==="cell")||{value:0};const rs=components.filter(c=>c.type!=="cell");let R=0;if(!rs.length)R=Infinity;else if(layout==="series")R=rs.reduce((a,c)=>a+c.value,0);else R=1/rs.reduce((a,c)=>a+1/c.value,0);const I=Number.isFinite(R)&&R>0?cell.value/R:0;return {V:cell.value,R,I,rs};}
  function compReading(c){const q=circuit();if(c.type==="cell")return {I:q.I,V:q.V,R:0};if(layout==="series")return {I:q.I,V:q.I*c.value,R:c.value};return {I:q.V/c.value,V:q.V,R:c.value};}
  function wires(){const svg=$("#sandboxWires"),board=$("#sandboxBoard");if(!svg||!board)return;const w=board.clientWidth,h=board.clientHeight;svg.setAttribute("viewBox",`0 0 ${w} ${h}`);const pts=components.map(c=>({c,x:c.x/100*w+42,y:c.y/100*h+30}));let lines="";if(layout==="series"&&pts.length>1){const sorted=[...pts].sort((a,b)=>a.x-b.x);for(let i=0;i<sorted.length-1;i++)lines+=`<path d="M${sorted[i].x} ${sorted[i].y} L${sorted[i+1].x} ${sorted[i+1].y}"/>`;lines+=`<path d="M${sorted[0].x} ${sorted[0].y} L${sorted[0].x} ${h-18} L${sorted.at(-1).x} ${h-18} L${sorted.at(-1).x} ${sorted.at(-1).y}"/>`;}else if(layout==="parallel"&&pts.length){const cell=pts.find(p=>p.c.type==="cell"),branches=pts.filter(p=>p.c.type!=="cell");if(cell){const top=38,bottom=h-35;lines+=`<path d="M${cell.x} ${cell.y} L${cell.x} ${top} L${w-45} ${top} M${cell.x} ${cell.y} L${cell.x} ${bottom} L${w-45} ${bottom}"/>`;for(const p of branches)lines+=`<path d="M${p.x} ${top} L${p.x} ${p.y-30} M${p.x} ${p.y+30} L${p.x} ${bottom}"/>`;}}svg.innerHTML=lines;}
  function render(){const b=$("#sandboxBoard");if(!b)return;b.querySelectorAll(".sandbox-component").forEach(x=>x.remove());for(const c of components){const t=types[c.type],el=document.createElement("button");el.className=`sandbox-component ${selected===c.id?"selected":""}`;el.dataset.sbId=c.id;el.style.left=c.x+"%";el.style.top=c.y+"%";el.innerHTML=`<strong>${t.symbol}</strong><span>${t.label}</span><small>${c.value} ${t.unit}</small>`;b.appendChild(el);}wires();renderInspector();}
  function renderInspector(){const c=components.find(x=>x.id===selected),q=circuit();if(c){const r=compReading(c),t=types[c.type];$("#sandboxInspector").innerHTML=`<p><strong>${t.label}</strong></p><label class="labplus-mini">Component value<input id="sandboxValue" type="number" step="0.1" value="${c.value}"></label><div class="reading-strip"><div><strong>${r.I.toFixed(3)} A</strong><span>current</span></div><div><strong>${r.V.toFixed(3)} V</strong><span>p.d.</span></div><div><strong>${r.R.toFixed(2)} Ω</strong><span>resistance</span></div></div>`;}else $("#sandboxInspector").innerHTML="<p class='labplus-note'>Select a component.</p>";$("#sandboxSummary").innerHTML=`<p><strong>${layout==="series"?"Series":"Parallel"} network</strong></p><p>Total resistance: <strong>${Number.isFinite(q.R)?q.R.toFixed(3):"—"} Ω</strong></p><p>Supply: <strong>${q.V.toFixed(2)} V</strong></p><p>Total current: <strong>${q.I.toFixed(3)} A</strong></p>`;$$('[data-sb-layout]').forEach(x=>x.classList.toggle("primary",x.dataset.sbLayout===layout));}
  function bindDrag(el){const board=$("#sandboxBoard"),id=Number(el.dataset.sbId);let down=false;const move=e=>{if(!down)return;const r=board.getBoundingClientRect(),c=components.find(x=>x.id===id);if(!c)return;c.x=Math.max(1,Math.min(88,(e.clientX-r.left)/r.width*100));c.y=Math.max(8,Math.min(80,(e.clientY-r.top)/r.height*100));el.style.left=c.x+"%";el.style.top=c.y+"%";wires();};el.addEventListener("pointerdown",e=>{down=true;selected=id;$$('.sandbox-component').forEach(x=>x.classList.toggle('selected',Number(x.dataset.sbId)===id));renderInspector();el.setPointerCapture?.(e.pointerId);});el.addEventListener("pointermove",move);el.addEventListener("pointerup",()=>{down=false;renderInspector();});el.addEventListener("pointercancel",()=>down=false);}
  function bind(){document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.sbAdd){const t=types[b.dataset.sbAdd];components.push({id:nextId++,type:b.dataset.sbAdd,x:25+Math.random()*50,y:20+Math.random()*55,value:t.value});selected=components.at(-1).id;render();return;}if(b.dataset.sbLayout){layout=b.dataset.sbLayout;render();return;}if(b.dataset.sbId){selected=Number(b.dataset.sbId);renderInspector();$$('.sandbox-component').forEach(x=>x.classList.toggle('selected',Number(x.dataset.sbId)===selected));return;}if(b.id==="sandboxDelete"){components=components.filter(c=>c.id!==selected);selected=components[0]?.id||null;render();return;}if(b.id==="sandboxReset"){components=[{id:1,type:"cell",x:10,y:45,value:9},{id:2,type:"resistor",x:42,y:25,value:10},{id:3,type:"resistor",x:42,y:66,value:15}];layout="series";nextId=4;selected=2;render();return;}});document.addEventListener("change",e=>{if(e.target.id==="sandboxValue"){const c=components.find(x=>x.id===selected);if(c){c.value=Math.max(.1,Number(e.target.value)||.1);render();}}});const obs=new MutationObserver(()=>{$$(".sandbox-component").forEach(el=>{if(!el.dataset.dragBound){el.dataset.dragBound="1";bindDrag(el);}});});obs.observe($("#sandboxBoard"),{childList:true});$$('.sandbox-component').forEach(el=>{el.dataset.dragBound="1";bindDrag(el);});window.addEventListener("resize",wires);}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",inject);else inject();
})();

(() => {
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const fmt=(v,d=3)=>Number.isFinite(v)?Number(v.toFixed(d)).toString():"—";
  const benches={
    charge:{title:"Current and conduction bench",note:"A physical circuit view paired with the microscopic model.",setup:["DC supply and ammeter are in series with the test resistor.","Voltmeter is connected in parallel across the resistor.","Current is conventional current; conduction electrons drift in the opposite direction."],state:{supply:6,resistance:12,time:20,temp:293,switchOn:true},calc:s=>{const I=s.switchOn?s.supply/s.resistance:0,Q=I*s.time;return {I,V:s.switchOn?s.supply:0,R:s.resistance,Q,W:s.supply*Q};}},
    iv:{title:"I–V characteristics apparatus",note:"Use a variable resistor/supply to change p.d.; ammeter is series, voltmeter is parallel across the test component.",setup:["Ammeter in series measures current through the component.","Voltmeter is connected across the component.","Use the rheostat to change the operating point and reverse the supply polarity when negative values are required."],state:{voltage:2,baseR:20,component:0,switchOn:true},calc:s=>{let I=0;if(s.switchOn){if(s.component===0)I=s.voltage/s.baseR;if(s.component===1)I=s.voltage/(s.baseR*(1+.05*Math.abs(s.voltage)));if(s.component===2){if(s.voltage>.55)I=Math.min(1.5,.018*(Math.exp((s.voltage-.55)*1.25)-1));else if(s.voltage<0)I=-.0002*Math.abs(s.voltage);}}return {I,V:s.switchOn?s.voltage:0,R:Math.abs(I)>1e-7?Math.abs(s.voltage/I):Infinity};}},
    resistivity:{title:"Required Practical 5 · resistivity bench",note:"Modelled on the AQA arrangement: straight resistance wire on a metre ruler, movable crocodile clip, micrometer, ammeter and voltmeter.",setup:["Use a low-voltage DC supply; ammeter is in series.","Voltmeter measures the p.d. across the selected length of test wire.","Measure diameter at several positions with a micrometer and open the switch between readings to limit heating."],state:{length:.5,diameter:.25,supply:1.5,temp:293,switchOn:false},calc:s=>{const rho=4.8e-7*(1+.0038*(s.temp-293)),A=Math.PI*(s.diameter/1000)**2/4,R=rho*s.length/A,I=s.switchOn?s.supply/R:0;return {I,V:s.switchOn?s.supply:0,R,rho,A};}},
    circuits:{title:"Series and parallel component bench",note:"Move between the two real wiring arrangements and inspect junction behaviour.",setup:["In series, the same current passes through both resistors.","In parallel, both branches share the same p.d.","Ammeter position determines which current is measured; voltmeter goes across the component or supply."],state:{supply:9,r1:10,r2:15,parallel:false,switchOn:true},calc:s=>{let R,I,I1,I2;if(s.parallel){R=s.r1*s.r2/(s.r1+s.r2);I=s.switchOn?s.supply/R:0;I1=s.switchOn?s.supply/s.r1:0;I2=s.switchOn?s.supply/s.r2:0;}else{R=s.r1+s.r2;I=s.switchOn?s.supply/R:0;I1=I2=I;}return {I,V:s.switchOn?s.supply:0,R,I1,I2,P=s.supply*I};}},
    divider:{title:"Potential divider sensor bench",note:"Two series components across a supply, with Vout measured across the lower component.",setup:["R1 and the sensor/fixed resistor are connected in series across Vin.","The voltmeter reads Vout across the lower component.","For an NTC or LDR, change the stimulus and observe the resistance and Vout response."],state:{vin:9,r1:2000,r2:4000,sensor:0,stimulus:50,switchOn:true},calc:s=>{let R2=s.r2;if(s.sensor===1)R2=s.r2*Math.exp(-.018*(s.stimulus-50));if(s.sensor===2)R2=s.r2/(.35+1.3*s.stimulus/100);const I=s.switchOn?s.vin/(s.r1+R2):0,Vout=I*R2;return {I,V:Vout,R:R2,Vout};}},
    internal:{title:"Required Practical 6 · emf and internal resistance",note:"Modelled on the AQA set-up: cell, switch, ammeter and variable resistor in series; voltmeter across the cell terminals.",setup:["Keep the switch open while adjusting the circuit and between readings.","Close the switch only to read terminal p.d. V and current I.","Vary the external resistance to obtain a range of I values; plot V against I. Intercept = emf and gradient = −r."],state:{emf:6,r:1,load:8,switchOn:false},calc:s=>{const I=s.switchOn?s.emf/(s.load+s.r):0,V=s.emf-I*s.r;return {I,V,R:s.load,lost:I*s.r};}}
  };
  let active="charge",data={};
  const componentNames=["Ohmic resistor","Filament lamp","Diode"];
  const sensorNames=["Fixed resistor","NTC thermistor","LDR"];

  function style(){if($("#realLabStyle"))return;const st=document.createElement("style");st.id="realLabStyle";st.textContent=`
  .real-lab{margin:16px 0 22px;border:1px solid var(--border);border-radius:20px;overflow:hidden;background:#07111f;box-shadow:var(--shadow)}
  .real-lab-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;padding:16px;background:linear-gradient(145deg,#10233a,#091827)}.real-lab-head h3{margin:4px 0}.real-lab-head p{margin:0;color:var(--muted);max-width:760px}.real-lab-badge{padding:7px 10px;border:1px solid #42617f;border-radius:999px;font-size:.72rem;font-weight:900;color:#c9edff;white-space:nowrap}
  .real-lab-grid{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(300px,.55fr);gap:0}.real-bench{position:relative;min-height:500px;padding:22px;background:linear-gradient(90deg,rgba(255,255,255,.025) 1px,transparent 1px),linear-gradient(#8c5f3a,#6f472d);background-size:110px 100%,100% 100%;overflow:hidden}.real-bench:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,rgba(255,255,255,.12),transparent 12%,rgba(0,0,0,.12));pointer-events:none}.real-side{padding:15px;border-left:1px solid var(--border);background:#091827;display:grid;gap:11px;align-content:start}.real-card{border:1px solid var(--border);border-radius:14px;padding:12px;background:#071522}.real-card h4{margin:0 0 7px}.real-card ul{margin:0;padding-left:19px}.real-card li{margin:5px 0;font-size:.8rem}.real-controls{display:grid;gap:8px}.real-control label{display:flex;justify-content:space-between;gap:8px;font-size:.76rem;font-weight:850}.real-control input[type=range]{width:100%;margin-top:6px}.real-control select{width:100%;margin-top:5px;background:#06111e;color:var(--text);border:1px solid #31506e;border-radius:9px;padding:7px}.real-actions{display:flex;gap:7px;flex-wrap:wrap}.real-data{max-height:150px;overflow:auto}.real-data table{width:100%;border-collapse:collapse;font-size:.72rem}.real-data th,.real-data td{padding:6px;border-bottom:1px solid rgba(130,160,190,.18);text-align:right}.real-data th:first-child,.real-data td:first-child{text-align:left}
  .meter-real{position:absolute;width:104px;height:145px;border-radius:17px;background:linear-gradient(145deg,#f4c23b,#d89c0d);border:2px solid #4f3d08;box-shadow:0 8px 18px rgba(0,0,0,.35);z-index:3}.meter-screen{position:absolute;left:14px;right:14px;top:16px;height:38px;border-radius:5px;background:#a8bba2;border:5px solid #242b2c;color:#102015;font-family:Consolas,monospace;font-weight:900;font-size:18px;display:grid;place-items:center}.meter-dial{position:absolute;left:31px;top:69px;width:42px;height:42px;border-radius:50%;background:radial-gradient(circle,#4d5152 0 28%,#171b1c 30% 60%,#4b5152 62%);border:3px solid #222;transform:rotate(-28deg)}.meter-label{position:absolute;bottom:9px;left:0;right:0;text-align:center;color:#1e210f;font-size:11px;font-weight:950}.jack{position:absolute;bottom:16px;width:12px;height:12px;border-radius:50%;border:3px solid #1e2224;background:#a00000}.jack.black{background:#111}.jack.j1{left:22px}.jack.j2{right:22px}
  .supply-real{position:absolute;width:145px;height:105px;border-radius:13px;background:linear-gradient(145deg,#d8dde1,#89949d);border:2px solid #3d474f;box-shadow:0 8px 18px rgba(0,0,0,.3);z-index:3}.supply-real .display{position:absolute;left:15px;top:17px;width:68px;height:30px;background:#1a2723;color:#85ffc5;border:3px solid #2f3938;border-radius:4px;font-family:Consolas,monospace;display:grid;place-items:center;font-weight:900}.supply-real .knob{position:absolute;right:16px;top:22px;width:36px;height:36px;border-radius:50%;background:radial-gradient(circle,#d8dde1 0 25%,#59636a 27% 100%);border:3px solid #3d474f}.supply-real .terminal{position:absolute;bottom:15px;width:16px;height:16px;border-radius:50%;border:4px solid #333}.supply-real .red{left:30px;background:#c71922}.supply-real .black{left:62px;background:#101010}.equip-label{position:absolute;left:8px;right:8px;bottom:5px;text-align:center;font-size:10px;font-weight:900;color:#202b31}
  .rheostat-real{position:absolute;width:180px;height:72px;border-radius:10px;background:linear-gradient(#3d2c20,#221811);border:2px solid #1b120d;box-shadow:0 8px 14px rgba(0,0,0,.3);z-index:3}.rheostat-coil{position:absolute;left:23px;right:23px;top:23px;height:20px;border-radius:4px;background:repeating-linear-gradient(90deg,#c27936 0 5px,#6c3518 5px 9px);border:2px solid #40200f}.rheostat-slider{position:absolute;top:10px;width:18px;height:50px;background:linear-gradient(90deg,#bbb,#eee,#888);border:2px solid #4d555a;border-radius:4px;cursor:ew-resize;touch-action:none}.rheostat-real .equip-label{color:#e7d8cb}
  .switch-real{position:absolute;width:92px;height:58px;border-radius:9px;background:#181c1f;border:2px solid #090b0d;box-shadow:0 7px 13px rgba(0,0,0,.32);z-index:4;cursor:pointer}.switch-post{position:absolute;bottom:10px;width:13px;height:13px;border-radius:50%;background:#c8d2d7;border:2px solid #555}.switch-post.a{left:17px}.switch-post.b{right:17px}.switch-arm{position:absolute;left:28px;top:26px;width:42px;height:6px;border-radius:4px;background:#d6dde0;transform-origin:left center;transform:rotate(-24deg);transition:.18s}.switch-real.closed .switch-arm{transform:rotate(0deg)}.switch-state{position:absolute;top:5px;left:0;right:0;text-align:center;color:#cdd7dc;font-size:10px;font-weight:900}
  .cell-real{position:absolute;width:110px;height:68px;border-radius:10px;background:#eceff1;border:2px solid #59636a;box-shadow:0 7px 15px rgba(0,0,0,.3);z-index:3}.battery{position:absolute;width:25px;height:47px;top:10px;border-radius:4px;background:linear-gradient(90deg,#d4d4d4,#f4f4f4,#b7b7b7);border:1px solid #555}.battery.one{left:21px}.battery.two{left:59px}.battery:before{content:"";position:absolute;left:7px;top:-5px;width:10px;height:5px;background:#555}.cell-real .equip-label{color:#2a3439}
  .resistor-real{position:absolute;width:115px;height:42px;border-radius:9px;background:linear-gradient(#d5ad73,#b77a36);border:2px solid #5f3b18;box-shadow:0 6px 12px rgba(0,0,0,.25);z-index:3}.resistor-real:before,.resistor-real:after{content:"";position:absolute;top:18px;width:28px;height:4px;background:#cfd4d7}.resistor-real:before{left:-29px}.resistor-real:after{right:-29px}.resistor-real span{display:grid;place-items:center;height:100%;color:#2b1a0b;font-weight:950;font-size:12px}.lamp-real{position:absolute;width:86px;height:105px;z-index:3}.lamp-bulb{position:absolute;left:16px;top:0;width:56px;height:64px;border-radius:50%;background:radial-gradient(circle at 40% 35%,#fff7bf,#eab34f 46%,#81561d 75%);border:3px solid #c1c7ca;box-shadow:0 0 22px rgba(255,200,80,.28)}.lamp-base{position:absolute;left:27px;top:61px;width:35px;height:37px;background:repeating-linear-gradient(#b5bcc0 0 5px,#777f83 5px 9px);border-radius:4px}.diode-real{position:absolute;width:105px;height:45px;border-radius:8px;background:#1b2227;border:2px solid #59656d;z-index:3;color:#aee8ff;display:grid;place-items:center;font-weight:900}.sensor-real{position:absolute;width:105px;height:55px;border-radius:8px;background:#162630;border:2px solid #5e859d;z-index:3;color:#ccefff;display:grid;place-items:center;font-weight:900}
  .ruler-real{position:absolute;left:9%;right:8%;height:54px;background:linear-gradient(#e7d9a3,#c6aa64);border:2px solid #6d5a25;box-shadow:0 6px 12px rgba(0,0,0,.25);z-index:2}.ruler-real .ticks{position:absolute;inset:0;background:repeating-linear-gradient(90deg,transparent 0 9px,#4b401f 9px 10px)}.wire-real{position:absolute;left:10%;right:9%;height:5px;background:linear-gradient(#de9a5c,#8e4c24);box-shadow:0 2px 4px rgba(0,0,0,.35);z-index:4}.clip-real{position:absolute;width:28px;height:56px;transform:translateX(-50%);z-index:6;cursor:ew-resize;touch-action:none}.clip-real:before{content:"";position:absolute;left:5px;top:12px;width:17px;height:34px;background:linear-gradient(90deg,#bbb,#eee,#777);clip-path:polygon(0 0,100% 12%,68% 50%,100% 88%,0 100%,25% 50%)}.clip-real:after{content:"";position:absolute;left:9px;top:0;width:10px;height:20px;border-radius:5px;background:#b6111b}.micrometer-real{position:absolute;width:150px;height:90px;z-index:3}.micro-frame{position:absolute;left:0;top:8px;width:76px;height:70px;border:14px solid #b8c2c8;border-right:0;border-radius:38px 0 0 38px}.micro-spindle{position:absolute;left:61px;top:38px;width:55px;height:10px;background:#dde4e7}.micro-thimble{position:absolute;left:105px;top:25px;width:45px;height:37px;background:repeating-linear-gradient(90deg,#d8dfe2 0 4px,#9da7ac 4px 6px);border:2px solid #59656b;border-radius:4px;cursor:ew-resize}.micro-read{position:absolute;top:72px;left:72px;background:#111d21;color:#a8ffcb;padding:4px 7px;border-radius:4px;font:700 11px Consolas}
  .lead-svg{position:absolute;inset:0;width:100%;height:100%;z-index:1;pointer-events:none}.lead-red,.lead-black{fill:none;stroke-width:5;stroke-linecap:round;filter:drop-shadow(0 2px 2px rgba(0,0,0,.3))}.lead-red{stroke:#cf2834}.lead-black{stroke:#171a1d}.bench-title{position:absolute;left:18px;top:12px;color:rgba(255,255,255,.85);font-size:12px;font-weight:900;z-index:8;background:rgba(0,0,0,.28);padding:5px 8px;border-radius:7px}.interactive-tag{position:absolute;right:16px;top:12px;z-index:8;background:#63d9a4;color:#07111f;border-radius:999px;padding:5px 8px;font-size:10px;font-weight:950}.bench-instruction{position:absolute;left:18px;right:18px;bottom:14px;z-index:8;background:rgba(5,13,22,.88);border:1px solid rgba(174,232,255,.25);border-radius:9px;color:#e4eff7;padding:7px 9px;font-size:11px}.range-select{display:flex;gap:5px;flex-wrap:wrap}.range-select button{border:1px solid #36536e;background:#071522;color:#dceaff;border-radius:7px;padding:5px 7px;font-size:10px}.range-select button.active{border-color:#67c7ff;background:#12304e}.overload{color:#ff7b87!important}
  @media(max-width:950px){.real-lab-grid{grid-template-columns:1fr}.real-side{border-left:0;border-top:1px solid var(--border)}.real-bench{min-height:470px}}@media(max-width:620px){.real-bench{min-height:430px;padding:12px}.meter-real{transform:scale(.82);transform-origin:top left}.supply-real{transform:scale(.82);transform-origin:top left}.real-lab-head{flex-direction:column}}
  `;document.head.appendChild(st);}

  function activeSim(){return $(".sim-tab.active")?.dataset.sim||active;}
  function state(){active=activeSim();return benches[active].state;}
  function calc(){return benches[active].calc(state());}
  function setState(patch){Object.assign(state(),patch);render();}
  function makeMeter(cls,label,value,x,y,range){const over=Math.abs(value)>range;return `<div class="meter-real ${cls}" style="left:${x}%;top:${y}%"><div class="meter-screen ${over?"overload":""}">${over?"OL":fmt(value,3)}</div><div class="meter-dial"></div><div class="jack j1"></div><div class="jack black j2"></div><div class="meter-label">${label}</div></div>`;}
  function leadSvg(paths){return `<svg class="lead-svg" viewBox="0 0 1000 500" preserveAspectRatio="none">${paths.map(p=>`<path class="${p[0]}" d="${p[1]}"/>`).join("")}</svg>`;}
  function supply(v,x,y){return `<div class="supply-real" style="left:${x}%;top:${y}%"><div class="display">${fmt(v,1)} V</div><div class="knob"></div><div class="terminal red"></div><div class="terminal black"></div><div class="equip-label">LOW-VOLTAGE DC SUPPLY</div></div>`;}
  function sw(on,x,y){return `<button class="switch-real ${on?"closed":""}" data-real-action="switch" style="left:${x}%;top:${y}%"><span class="switch-state">${on?"CLOSED":"OPEN"}</span><span class="switch-post a"></span><span class="switch-post b"></span><span class="switch-arm"></span></button>`;}
  function rheostat(value,min,max,x,y){const pct=(value-min)/(max-min)*100;return `<div class="rheostat-real" style="left:${x}%;top:${y}%"><div class="rheostat-coil"></div><div class="rheostat-slider" data-real-drag="rheostat" style="left:calc(13px + ${pct} * 1.32px)"></div><div class="equip-label">SLIDE RHEOSTAT</div></div>`;}
  function resistor(label,x,y){return `<div class="resistor-real" style="left:${x}%;top:${y}%"><span>${label}</span></div>`;}

  function benchHtml(){const s=state(),c=calc();let inner="";let instruction="";
    if(active==="charge"){
      inner=leadSvg([["lead-red","M180 160 C290 130 360 160 455 190"],["lead-black","M575 190 C690 220 730 180 820 180"],["lead-red","M520 210 C560 300 665 320 730 330"],["lead-black","M455 210 C410 300 325 320 275 330"]])+supply(s.supply,5,23)+resistor(`${s.resistance} Ω`,44,36)+makeMeter("ammeter-real","AMMETER / A",c.I,74,20,2)+makeMeter("voltmeter-real","VOLTMETER / V",c.V,68,58,20)+sw(s.switchOn,27,65);instruction="Click the switch. Adjust supply and resistance in the controls; observe current, charge and energy transfer.";
    }
    if(active==="iv"){
      const test=s.component===0?resistor("OHMIC RESISTOR",43,37):s.component===1?`<div class="lamp-real" style="left:45%;top:31%"><div class="lamp-bulb"></div><div class="lamp-base"></div></div>`:`<div class="diode-real" style="left:44%;top:38%">DIODE ▶|</div>`;
      inner=leadSvg([["lead-red","M180 150 C270 100 365 125 440 190"],["lead-black","M550 190 C650 150 690 135 805 175"],["lead-red","M470 210 C470 300 630 330 710 330"],["lead-black","M535 210 C550 285 650 300 710 300"]])+supply(Math.abs(s.voltage),5,20)+rheostat(Math.abs(s.voltage),0,8,24,62)+test+makeMeter("ammeter-real","AMMETER / A",c.I,76,18,2)+makeMeter("voltmeter-real","VOLTMETER / V",c.V,72,58,20)+sw(s.switchOn,24,24);instruction="Drag the rheostat slider or use the control. Swap the test component and capture enough points to see each I–V curve.";
    }
    if(active==="resistivity"){
      const pct=10+s.length*78;inner=leadSvg([["lead-red","M180 155 C270 130 290 190 340 215"],["lead-black","M350 240 C270 310 190 285 150 235"],["lead-red",`M${pct*10} 260 C${pct*10} 330 705 310 735 330`],["lead-black","M155 260 C170 340 600 360 735 300"]])+supply(s.supply,4,20)+makeMeter("ammeter-real","AMMETER / A",c.I,74,18,2)+makeMeter("voltmeter-real","VOLTMETER / V",c.V,74,58,20)+`<div class="ruler-real" style="top:50%"><div class="ticks"></div></div><div class="wire-real" style="top:47.5%"></div><div class="clip-real" data-real-drag="clip" style="left:${pct}%;top:38%"></div><div class="clip-real" style="left:10%;top:38%"></div><div class="micrometer-real" style="left:37%;top:66%"><div class="micro-frame"></div><div class="micro-spindle"></div><div class="micro-thimble" data-real-drag="micrometer"></div><div class="micro-read">${s.diameter.toFixed(2)} mm</div></div>`+sw(s.switchOn,27,18);instruction="Drag the red crocodile clip along the ruler. Drag the micrometer thimble to change/read diameter. Open the switch after taking a reading to reduce heating.";
    }
    if(active==="circuits"){
      const paths=s.parallel?[["lead-red","M180 165 C250 115 300 100 360 105 M360 105 L360 350 M620 105 L620 350 M360 105 L620 105 M360 350 L620 350"],["lead-black","M620 350 C720 330 770 245 815 180"]]:[["lead-red","M180 165 C280 140 340 185 420 205"],["lead-black","M650 205 C720 210 750 195 815 180"]];inner=leadSvg(paths)+supply(s.supply,5,24)+resistor(`R₁ ${s.r1} Ω`,39,s.parallel?17:37)+resistor(`R₂ ${s.r2} Ω`,61,s.parallel?62:37)+makeMeter("ammeter-real","TOTAL CURRENT / A",c.I,77,18,2)+sw(s.switchOn,23,66);instruction="Switch between series and parallel in the controls. Change R₁ and R₂ and compare total current and branch currents.";
    }
    if(active==="divider"){
      const sensor=s.sensor===0?resistor(`R₂ ${fmt(c.R,0)} Ω`,46,56):`<div class="sensor-real" style="left:46%;top:56%">${sensorNames[s.sensor]}<br>${fmt(c.R,0)} Ω</div>`;inner=leadSvg([["lead-red","M180 155 C300 100 450 105 505 125"],["lead-black","M505 350 C350 365 230 285 180 220"],["lead-red","M560 240 C650 240 675 300 735 315"],["lead-black","M480 240 C410 290 580 340 735 285"]])+supply(s.vin,5,22)+resistor(`R₁ ${s.r1} Ω`,46,19)+sensor+makeMeter("voltmeter-real","VOUT / V",c.Vout,74,49,20)+sw(s.switchOn,25,22)+`<div class="interactive-tag">stimulus ${s.stimulus}%</div>`;instruction="Choose fixed resistor, NTC or LDR. Change temperature/light stimulus and watch the output voltage respond.";
    }
    if(active==="internal"){
      inner=leadSvg([["lead-red","M220 330 C290 350 330 315 390 300"],["lead-red","M480 300 C520 300 535 240 550 210"],["lead-red","M650 210 C730 210 760 170 820 170"],["lead-black","M820 215 C760 315 630 350 520 355"],["lead-black","M520 355 C400 370 320 360 220 350"],["lead-red","M220 320 C270 210 610 145 720 315"],["lead-black","M220 365 C330 430 620 410 720 345"]])+`<div class="cell-real" style="left:8%;top:62%"><div class="battery one"></div><div class="battery two"></div><div class="equip-label">CELL / BATTERY</div></div>`+sw(s.switchOn,27,61)+rheostat(s.load,.5,25,43,56)+makeMeter("ammeter-real","AMMETER / A",c.I,78,20,2)+makeMeter("voltmeter-real","TERMINAL P.D. / V",c.V,72,61,20);instruction="AQA layout: cell, switch, ammeter and variable resistor in series; voltmeter across the cell. Keep the switch open between readings.";
    }
    return `<div class="bench-title">${benches[active].title}</div><div class="interactive-tag">INTERACTIVE EQUIPMENT</div>${inner}<div class="bench-instruction">${instruction}</div>`;
  }

  function controlsHtml(){const s=state();
    const range=(k,label,min,max,step,u)=>`<div class="real-control"><label><span>${label}</span><strong>${fmt(s[k],step<.1?2:1)} ${u}</strong></label><input type="range" data-real-control="${k}" min="${min}" max="${max}" step="${step}" value="${s[k]}"></div>`;
    let h="";
    if(active==="charge")h=range("supply","Supply p.d.",1,12,.5,"V")+range("resistance","Resistance",2,30,1,"Ω")+range("time","Time",1,60,1,"s")+range("temp","Temperature",273,700,5,"K");
    if(active==="iv")h=range("voltage","Applied p.d.",-8,8,.1,"V")+range("baseR","Base resistance",5,50,1,"Ω")+`<div class="real-control"><label>Test component</label><select data-real-control="component">${componentNames.map((n,i)=>`<option value="${i}" ${s.component===i?"selected":""}>${n}</option>`).join("")}</select></div>`;
    if(active==="resistivity")h=range("length","Wire length",.2,.9,.1,"m")+range("diameter","Diameter",.20,.60,.01,"mm")+range("supply","Supply p.d.",.5,3,.1,"V")+range("temp","Wire temperature",293,350,1,"K");
    if(active==="circuits")h=range("supply","Supply",1,15,.5,"V")+range("r1","R₁",1,30,1,"Ω")+range("r2","R₂",1,30,1,"Ω")+`<div class="real-control"><label>Arrangement</label><select data-real-control="parallel"><option value="0" ${!s.parallel?"selected":""}>Series</option><option value="1" ${s.parallel?"selected":""}>Parallel</option></select></div>`;
    if(active==="divider")h=range("vin","Input p.d.",1,15,.5,"V")+range("r1","R₁",500,10000,500,"Ω")+range("r2","Base R₂",500,10000,500,"Ω")+range("stimulus","Temperature / light",0,100,1,"%")+`<div class="real-control"><label>Lower component</label><select data-real-control="sensor">${sensorNames.map((n,i)=>`<option value="${i}" ${s.sensor===i?"selected":""}>${n}</option>`).join("")}</select></div>`;
    if(active==="internal")h=range("emf","EMF",1,12,.1,"V")+range("r","Internal resistance",.1,5,.1,"Ω")+range("load","External resistance",.5,25,.5,"Ω");
    return h;
  }

  function readingsHtml(){const c=calc();let cells=[[`I`,`${fmt(c.I,4)} A`],[`V`,`${fmt(c.V,4)} V`],[`R`,`${fmt(c.R,4)} Ω`]];if(active==="charge")cells.push([`Q`,`${fmt(c.Q,3)} C`],[`W`,`${fmt(c.W,3)} J`]);if(active==="resistivity")cells.push([`ρ`,`${c.rho.toExponential(3)} Ω m`]);if(active==="circuits")cells.push([`I₁`,`${fmt(c.I1,3)} A`],[`I₂`,`${fmt(c.I2,3)} A`]);if(active==="divider")cells.push([`Vout`,`${fmt(c.Vout,3)} V`]);if(active==="internal")cells.push([`lost volts`,`${fmt(c.lost,3)} V`]);return `<div class="reading-strip">${cells.map(x=>`<div><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join("")}</div>`;}
  function dataHeaders(){if(active==="iv")return ["V / V","I / A","R / Ω"];if(active==="resistivity")return ["L / m","V / V","I / A","R / Ω"];if(active==="internal")return ["Rload / Ω","I / A","V / V","Ir / V"];return ["State","I / A","V / V","R / Ω"];}
  function capture(){const s=state(),c=calc();data[active]=data[active]||[];let row;if(active==="iv")row=[s.voltage,c.I,c.R];else if(active==="resistivity")row=[s.length,c.V,c.I,c.R];else if(active==="internal")row=[s.load,c.I,c.V,c.lost];else row=[data[active].length+1,c.I,c.V,c.R];data[active].push(row);render();}
  function tableHtml(){const rows=data[active]||[],heads=dataHeaders();return `<table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((v,i)=>`<td>${i===0&&typeof v==="string"?v:fmt(Number(v),4)}</td>`).join("")}</tr>`).join("")}</tbody></table>`;}

  function render(){active=activeSim();const b=benches[active],root=$("#realLabPro");if(!root)return;root.innerHTML=`<div class="real-lab-head"><div><span class="eyebrow">Real Equipment Bench</span><h3>${b.title}</h3><p>${b.note}</p></div><span class="real-lab-badge">AQA-correct layout where assessed</span></div><div class="real-lab-grid"><div class="real-bench" id="realBench">${benchHtml()}</div><aside class="real-side"><section class="real-card"><h4>Correct set-up</h4><ul>${b.setup.map(x=>`<li>${x}</li>`).join("")}</ul></section><section class="real-card"><h4>Direct controls</h4><div class="real-controls">${controlsHtml()}</div></section><section class="real-card"><h4>Live readings</h4>${readingsHtml()}<div class="range-select"><button class="active">2 A range</button><button class="active">20 V range</button><button>Ω range</button></div></section><section class="real-card"><h4>Experimental data</h4><div class="real-actions"><button class="button primary" data-real-action="capture">Take reading</button><button class="button" data-real-action="clear">Clear</button></div><div class="real-data">${tableHtml()}</div></section></aside></div>`;bindDrag();}
  function bindDrag(){const clip=$("[data-real-drag=clip]"),micro=$("[data-real-drag=micrometer]"),rh=$("[data-real-drag=rheostat]");if(clip){let down=false;clip.onpointerdown=e=>{down=true;clip.setPointerCapture?.(e.pointerId)};clip.onpointermove=e=>{if(!down)return;const r=$("#realBench").getBoundingClientRect(),pct=clamp((e.clientX-r.left)/r.width, .10,.88),length=clamp((pct-.10)/.78,.2,.9);benches.resistivity.state.length=Math.round(length*10)/10;render();};clip.onpointerup=()=>down=false;}
    if(micro){let down=false,startX=0,start=0;micro.onpointerdown=e=>{down=true;startX=e.clientX;start=benches.resistivity.state.diameter;micro.setPointerCapture?.(e.pointerId)};micro.onpointermove=e=>{if(!down)return;benches.resistivity.state.diameter=clamp(start+(e.clientX-startX)/400,.2,.6);render();};micro.onpointerup=()=>down=false;}
    if(rh){let down=false;rh.onpointerdown=e=>{down=true;rh.setPointerCapture?.(e.pointerId)};rh.onpointermove=e=>{if(!down)return;const box=rh.parentElement.getBoundingClientRect(),p=clamp((e.clientX-box.left)/box.width,0,1);if(active==="internal")benches.internal.state.load=.5+p*24.5;else if(active==="iv")benches.iv.state.voltage=-8+p*16;render();};rh.onpointerup=()=>down=false;}}

  function inject(){style();const lp=$("#labPlus");if(!lp||$("#realLabPro"))return;const sec=document.createElement("section");sec.id="realLabPro";sec.className="real-lab";lp.insertAdjacentElement("afterend",sec);render();
    document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.realAction==="switch"){state().switchOn=!state().switchOn;render();return;}if(b.dataset.realAction==="capture"){capture();return;}if(b.dataset.realAction==="clear"){data[active]=[];render();return;}if(b.classList.contains("sim-tab"))setTimeout(render,80);});
    document.addEventListener("input",e=>{const k=e.target.dataset.realControl;if(k===undefined)return;let v=Number(e.target.value);if(k==="parallel")v=Boolean(v);state()[k]=v;render();});document.addEventListener("change",e=>{const k=e.target.dataset.realControl;if(k===undefined)return;let v=Number(e.target.value);if(k==="parallel")v=Boolean(v);state()[k]=v;render();});
    const tabs=$("#simTabs");if(tabs)new MutationObserver(()=>{const a=activeSim();if(a!==active){active=a;render();}}).observe(tabs,{subtree:true,attributes:true,attributeFilter:["class"]});}
  const start=()=>{if(!$("#labPlus")){setTimeout(start,120);return;}inject();};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start);else start();
})();