'use strict';(()=>{
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const P=(a,b)=>b?Math.abs(a/b)*100:0,F=(v,d=3)=>Number(v).toFixed(d).replace(/\.0+$|(?<=\.[0-9]*?)0+$/,'');
function addBefore(el,html){el.insertAdjacentHTML('beforebegin',html)}
function addEnd(el,html){el.insertAdjacentHTML('beforeend',html)}
if(typeof equations!=='undefined'){
 equations.gradientUncertainty={title:'Gradient uncertainty',display:'percentage uncertainty = |m_best − m_worst| / |m_best| × 100%',meaning:'Compare the best-fit gradient with one steepest or shallowest worst acceptable line that remains consistent with the data/error bars.',steps:['Draw the best-fit line.','Draw one worst acceptable line.','Calculate both gradients using large triangles.','Find the percentage difference from the best gradient.'],example:'2.40 vs 2.55 gives 6.25%.'};
 equations.interceptUncertainty={title:'Intercept uncertainty',display:'percentage uncertainty = |c_best − c_worst| / |c_best| × 100%',meaning:'Use the intercepts from the best-fit line and the same worst acceptable line.',steps:['Read c_best.','Read c_worst.','Calculate the percentage difference.'],example:'1.10 vs 0.96 gives 12.7%.'};
}
if(typeof formulae!=='undefined'){
 const put=(id,o)=>{const i=formulae.findIndex(f=>f.id===id);i<0?formulae.push(o):formulae[i]=o};
 put('grad',{id:'grad',name:'Gradient absolute uncertainty',fields:[['best','Best gradient',2.40],['worst','Worst acceptable gradient',2.55]],calc:v=>({display:`|${v.best} − ${v.worst}|`,result:Math.abs(v.best-v.worst),unit:'gradient units',explain:'Difference between the best and worst acceptable gradients.'})});
 put('gradpct',{id:'gradpct',name:'Gradient percentage uncertainty',fields:[['best','Best gradient',2.40],['worst','Worst acceptable gradient',2.55]],calc:v=>({display:`|${v.best} − ${v.worst}| / |${v.best}| × 100`,result:P(v.best-v.worst,v.best),unit:'%',explain:'AQA practical method: best fit compared with one worst acceptable line.'})});
 put('int',{id:'int',name:'Intercept percentage uncertainty',fields:[['best','Best intercept',1.10],['worst','Worst acceptable intercept',0.96]],calc:v=>({display:`|${v.best} − ${v.worst}| / |${v.best}| × 100`,result:P(v.best-v.worst,v.best),unit:'%',explain:'Compare the best intercept with the intercept of the same worst acceptable line.'})});
}
if(typeof lessons!=='undefined'){
 const g=lessons.find(x=>x.id==='graphs');if(g){g.teach='Error bars show uncertainty in plotted coordinates. For AQA practical analysis, draw a best-fit line and one steepest or shallowest worst acceptable line still consistent with the error bars. Percentage gradient uncertainty = |m_best − m_worst|/|m_best| × 100%. Apply the same idea to the intercept.';g.worked='m_best = 2.40 and m_worst = 2.55 gives |2.40−2.55|/2.40 × 100 = 6.25%.';}
}
const nav=q('.main-nav'),spec=q('#view-spec');
if(nav&&!q('[data-view="dashboard"]')){const b=document.createElement('button');b.className='nav-button';b.dataset.view='dashboard';b.textContent='Dashboard';nav.insertBefore(b,nav.querySelector('[data-view="spec"]'));b.onclick=()=>{showView('dashboard');dash()}}
if(spec&&!q('#view-dashboard'))addBefore(spec,`<section class="view" id="view-dashboard"><div class="section-head"><div><span class="eyebrow">Personal learning analytics</span><h2>Progress & misconception dashboard</h2></div><p class="muted">Progress is stored only in this browser.</p></div><div class="dashboard-grid"><article class="panel pad"><h3>Course progress</h3><div class="dashboard-ring" id="dashboardRing"><strong id="dashboardPercent">0%</strong></div><p id="dashboardLessons" class="muted"></p></article><article class="panel pad"><h3>Question accuracy</h3><div class="stat-grid"><div><strong id="dashQuizAccuracy">—</strong><span>mastery quiz</span></div><div><strong id="dashSkillsAccuracy">—</strong><span>skills modes</span></div></div></article><article class="panel pad dashboard-wide"><h3>Misconception tracker</h3><div id="misconceptionList"></div></article><article class="panel pad dashboard-wide"><h3>Suggested next step</h3><div id="nextStepCard" class="next-step-card"></div></article></div></section>`);
const ps=q('#practicalSwitch'),pv=q('#view-practical');
if(ps&&!q('[data-practical="workspace"]'))addEnd(ps,'<button class="button" data-practical="workspace">Data workspace</button>');
if(pv&&!q('#practical-workspace'))addEnd(pv,`<div class="practical-panel hidden" id="practical-workspace"><div class="practical-grid"><article class="panel pad"><h3>Student data workspace</h3><p class="muted small">Enter x–y data with optional y uncertainties, then calculate a best-fit line and a worst acceptable line.</p><div class="table-scroll"><table class="data-table data-entry-table"><thead><tr><th>#</th><th>x</th><th>y</th><th>±Δy</th></tr></thead><tbody id="workspaceRows"></tbody></table></div><div class="button-row"><button class="button primary" id="plotWorkspace">Plot & analyse</button><button class="button" id="loadWorkspaceExample">Load example</button><button class="button" id="clearWorkspace">Clear</button><button class="button" id="downloadWorkspaceCsv">Download CSV</button></div><div class="practical-guidance"><strong>Paper 3 practice:</strong> compare the best line with a worst acceptable line, then judge whether the precision is adequate.</div></article><article class="panel pad"><h3>Graph and analysis</h3><div class="mini-graph large"><canvas id="workspaceCanvas"></canvas></div><div class="equation" id="workspaceSummary">Enter at least three points.</div></article></div></div>`);
if(q('[data-practical="workspace"]'))q('[data-practical="workspace"]').onclick=()=>{practicalSwitch('workspace');requestAnimationFrame(plotWork)};
const mt=q('#view-mastery .mastery-tabs'),mv=q('#view-mastery');
if(mt&&!q('[data-mastery="sigfig"]'))addEnd(mt,'<button class="button" data-mastery="sigfig">Significant figures</button><button class="button" data-mastery="challenge">Uncertainty challenge</button>');
if(mv&&!q('#mastery-sigfig'))addEnd(mv,`<div id="mastery-sigfig" class="hidden"><div class="skills-layout"><article class="panel pad"><span class="eyebrow">Precision</span><h3>Significant Figures Trainer</h3><p id="sigfigQuestion" class="skill-question"></p><label class="field"><span>Your answer</span><input id="sigfigInput" type="text" inputmode="decimal"></label><div class="button-row"><button class="button primary" id="checkSigfig">Check</button><button class="button" id="nextSigfig">New question</button></div><div id="sigfigFeedback" class="feedback hidden"></div></article><aside class="panel pad"><div class="stat-grid"><div><strong id="sigfigScore">0</strong><span>correct</span></div><div><strong id="sigfigAttempts">0</strong><span>attempts</span></div></div></aside></div></div><div id="mastery-challenge" class="hidden"><div class="skills-layout"><article class="panel pad"><span class="eyebrow">AQA uncertainty rules</span><h3>Uncertainty Challenge</h3><p id="challengeQuestion" class="skill-question"></p><div id="challengeChoices" class="choice-list"></div><div id="challengeFeedback" class="feedback hidden"></div><button class="button primary hidden" id="nextChallenge">Next challenge</button></article><aside class="panel pad"><div class="stat-grid"><div><strong id="challengeScore">0</strong><span>correct</span></div><div><strong id="challengeAttempts">0</strong><span>attempts</span></div></div></aside></div></div>`);
const base={quizAttempts:0,quizCorrect:0,wrong:{},sigAttempts:0,sigCorrect:0,chAttempts:0,chCorrect:0};let S={...base};try{S={...base,...JSON.parse(safeStorage.get('meV3Stats','{}'))}}catch{};S.wrong=S.wrong||{};
const save=()=>{safeStorage.set('meV3Stats',JSON.stringify(S));dash()},miss=k=>S.wrong[k]=(S.wrong[k]||0)+1;
if(q('#quizChoices'))q('#quizChoices').addEventListener('click',e=>{const b=e.target.closest('[data-choice]');if(!b||b.dataset.v3)return;b.dataset.v3='1';const z=quizzes[state.quizIndex],ok=+b.dataset.choice===z.answer;S.quizAttempts++;ok?S.quizCorrect++:miss(z.spec);save()});
function dash(){if(!q('#dashboardPercent'))return;const d=Math.round(state.completed.size/lessons.length*100);q('#dashboardPercent').textContent=d+'%';q('#dashboardLessons').textContent=`${state.completed.size} of ${lessons.length} lessons completed.`;q('#dashboardRing').style.background=`conic-gradient(var(--accent) ${d*3.6}deg,#15283b 0deg)`;q('#dashQuizAccuracy').textContent=S.quizAttempts?Math.round(S.quizCorrect/S.quizAttempts*100)+'%':'—';const a=S.sigAttempts+S.chAttempts,c=S.sigCorrect+S.chCorrect;q('#dashSkillsAccuracy').textContent=a?Math.round(c/a*100)+'%':'—';const w=Object.entries(S.wrong).sort((a,b)=>b[1]-a[1]),m=w[0]?.[1]||1;q('#misconceptionList').innerHTML=w.length?w.slice(0,6).map(([k,n])=>`<div class="misconception-row"><strong>${k}</strong><div class="misconception-bar"><span style="width:${n/m*100}%"></span></div><span>${n}</span></div>`).join(''):'<div class="dashboard-empty">No repeated misconceptions logged yet.</div>';let n;if(state.completed.size<lessons.length){const l=lessons.find(x=>!state.completed.has(x.id));n=`Continue with <strong>${l.title}</strong> and its linked simulation.`}else if(w.length)n=`Target <strong>${w[0][0]}</strong> in the Mastery Hub and Formula Coach.`;else n='Use the Student Data Workspace for Paper 3-style unfamiliar-data practice.';q('#nextStepCard').innerHTML=n}
const SF=[['Round 0.0048762 to 3 significant figures.',0.00488,'0.00488'],['Round 63842 to 2 significant figures.',64000,'64000'],['12.347 ± 0.6 cm: what value should be quoted?',12.3,'12.3 cm'],['Round 2.00651 to 4 significant figures.',2.007,'2.007'],['Round 9.96 × 10⁶ to 2 significant figures.',1e7,'1.0 × 10⁷'],['0.034728 ± 0.0004 m: what value should be quoted?',0.0347,'0.0347 m']];let si=0;
function rs(){const z=SF[si];q('#sigfigQuestion').textContent=z[0];q('#sigfigInput').value='';q('#sigfigFeedback').classList.add('hidden');q('#sigfigScore').textContent=S.sigCorrect;q('#sigfigAttempts').textContent=S.sigAttempts}
q('#checkSigfig').onclick=()=>{const z=SF[si],v=Number(q('#sigfigInput').value.trim()),ok=Number.isFinite(v)&&Math.abs(v-z[1])<=Math.max(Math.abs(z[1])*1e-9,1e-12);S.sigAttempts++;ok?S.sigCorrect++:miss('Significant figures');save();const f=q('#sigfigFeedback');f.className='feedback '+(ok?'good':'partial');f.innerHTML=`<strong>${ok?'Correct':'Not quite'}.</strong> Answer: <span class="sf-preview">${z[2]}</span>`;q('#sigfigScore').textContent=S.sigCorrect;q('#sigfigAttempts').textContent=S.sigAttempts};q('#nextSigfig').onclick=()=>{si=(si+1)%SF.length;rs()};
const CH=[['Propagation','Q=AB with 2% and 4% uncertainties. Q uncertainty?',['2%','4%','6%','8%'],2,'Add percentage uncertainties.'],['Propagation','Q=A+B with ΔA=0.2 N and ΔB=0.3 N. ΔQ?',['0.1 N','0.25 N','0.5 N','6%'],2,'Add absolute uncertainties.'],['Graph uncertainty','m_best=2.40, m_worst=2.55. Percentage uncertainty?',['3.1%','6.25%','12.5%','0.15%'],1,'Use |best−worst|/best × 100.'],['Errors','Repeating 20 times mainly reduces:',['random error','systematic zero error','calibration offset','unit error'],0,'Repeats reduce random scatter.'],['Units','1 kW h equals:',['3.60×10³ J','3.60×10⁶ J','3.60×10⁹ J','1000 J'],1,'1000 W × 3600 s.'],['Resolution','Finer resolution means:',['more accurate','smaller detectable change','no systematic error','no random error'],1,'Resolution is the smallest detectable change.']];let ci=0;
function rc(){const z=CH[ci];q('#challengeQuestion').innerHTML=`<span class="skill-badge">${z[0]}</span><br>${z[1]}`;q('#challengeChoices').innerHTML=z[2].map((x,i)=>`<button class="choice" data-ch="${i}">${x}</button>`).join('');q('#challengeFeedback').classList.add('hidden');q('#nextChallenge').classList.add('hidden');q('#challengeScore').textContent=S.chCorrect;q('#challengeAttempts').textContent=S.chAttempts;qa('[data-ch]').forEach(b=>b.onclick=()=>{const ok=+b.dataset.ch===z[3];S.chAttempts++;ok?S.chCorrect++:miss(z[0]);save();qa('[data-ch]').forEach((x,j)=>{x.disabled=true;if(j===z[3])x.classList.add('correct');if(x===b&&!ok)x.classList.add('wrong')});const f=q('#challengeFeedback');f.className='feedback '+(ok?'good':'partial');f.innerHTML=`<strong>${ok?'Correct':'Not quite'}.</strong> ${z[4]}`;f.classList.remove('hidden');q('#nextChallenge').classList.remove('hidden');q('#challengeScore').textContent=S.chCorrect;q('#challengeAttempts').textContent=S.chAttempts})}
q('#nextChallenge').onclick=()=>{ci=(ci+1)%CH.length;rc()};
qa('[data-mastery]').forEach(b=>b.onclick=()=>{const id=b.dataset.mastery;['quiz','extended','sigfig','challenge'].forEach(k=>{const e=q('#mastery-'+k);if(e)e.classList.toggle('hidden',id!==k)});qa('[data-mastery]').forEach(x=>x.classList.toggle('primary',x.dataset.mastery===id));if(id==='extended')renderExtended();if(id==='sigfig')rs();if(id==='challenge')rc()});
let W=Array.from({length:8},()=>({x:'',y:'',u:''}));
function rows(){q('#workspaceRows').innerHTML=W.map((r,i)=>`<tr><td>${i+1}</td><td><input data-x="${i}" value="${r.x}"></td><td><input data-y="${i}" value="${r.y}"></td><td><input data-u="${i}" value="${r.u}"></td></tr>`).join('');qa('[data-x]').forEach(e=>e.oninput=()=>W[+e.dataset.x].x=e.value);qa('[data-y]').forEach(e=>e.oninput=()=>W[+e.dataset.y].y=e.value);qa('[data-u]').forEach(e=>e.oninput=()=>W[+e.dataset.u].u=e.value)}
const pts=()=>W.map(r=>({x:+r.x,y:+r.y,u:Math.abs(+r.u||0),v:r.x!==''&&r.y!==''})).filter(p=>p.v&&Number.isFinite(p.x)&&Number.isFinite(p.y)).sort((a,b)=>a.x-b.x);
function plotWork(){const a=pts(),c=q('#workspaceCanvas');if(!c)return;const {x,w,h}=clearCanvas(c,'Student data workspace');axis(x,w,h);if(a.length<3){q('#workspaceSummary').textContent='Enter at least three valid points.';return}const b=linearRegression(a),f=a[0],l=a.at(-1),dx=l.x-f.x||1,steep=((l.y+l.u)-(f.y-f.u))/dx,shallow=((l.y-l.u)-(f.y+f.u))/dx,worst=Math.abs(steep-b.m)>=Math.abs(shallow-b.m)?steep:shallow,wb=worst===steep?(f.y-f.u)-worst*f.x:(f.y+f.u)-worst*f.x,minX=f.x,maxX=l.x,minY=Math.min(0,...a.map(p=>p.y-p.u)),maxY=Math.max(...a.map(p=>p.y+p.u)),pad=60,xm=z=>pad+(z-minX)/(maxX-minX||1)*(w-pad-30),ym=z=>h-pad-(z-minY)/(maxY-minY||1)*(h-pad-45);a.forEach(p=>{const X=xm(p.x),Y=ym(p.y),U=Math.abs(ym(p.y+p.u)-Y);x.strokeStyle='#7aa0bd';x.beginPath();x.moveTo(X,Y-U);x.lineTo(X,Y+U);x.stroke();x.fillStyle='#57d3ff';x.beginPath();x.arc(X,Y,4,0,Math.PI*2);x.fill()});const line=(m,c,col)=>{x.strokeStyle=col;x.lineWidth=2;x.beginPath();x.moveTo(xm(minX),ym(m*minX+c));x.lineTo(xm(maxX),ym(m*maxX+c));x.stroke()};line(b.m,b.b,'#8ce99a');line(worst,wb,'#ffd166');const gp=P(b.m-worst,b.m),ip=Math.abs(b.b)>1e-12?P(b.b-wb,b.b):null;q('#workspaceSummary').innerHTML=`Best: <strong>y=${F(b.m,4)}x ${b.b>=0?'+':'−'} ${F(Math.abs(b.b),4)}</strong><br>Worst acceptable gradient: <strong>${F(worst,4)}</strong> · gradient uncertainty: <strong>${F(gp,2)}%</strong>${ip===null?'':` · intercept uncertainty: <strong>${F(ip,2)}%</strong>`}`}
q('#plotWorkspace').onclick=plotWork;q('#loadWorkspaceExample').onclick=()=>{W=[.2,.3,.4,.5,.6,.7,.8,.9].map((x,i)=>({x:String(x),y:String([.90,1.12,1.30,1.49,1.72,1.89,2.13,2.30][i]),u:'.08'}));rows();plotWork()};q('#clearWorkspace').onclick=()=>{W=Array.from({length:8},()=>({x:'',y:'',u:''}));rows();q('#workspaceSummary').textContent='Enter at least three points.'};q('#downloadWorkspaceCsv').onclick=()=>{const a=pts();if(!a.length)return alert('Enter some data first.');const B=new Blob(['x,y,dy\n'+a.map(p=>`${p.x},${p.y},${p.u}`).join('\n')],{type:'text/csv'}),A=document.createElement('a');A.href=URL.createObjectURL(B);A.download='measurements-errors-data.csv';A.click()};
if(typeof drawGraphBench==='function')drawGraphBench=function(){const c=q('#graphBenchCanvas');if(!c)return;const {x,w,h}=clearCanvas(c,'Graph uncertainty bench');axis(x,w,h);if(!state.graphData.length){q('#graphBenchSummary').textContent='Generate a data set to begin.';return}const a=state.graphData,b=linearRegression(a),f=a[0],l=a.at(-1),dx=l.x-f.x,steep=((l.y+l.u)-(f.y-f.u))/dx,shallow=((l.y-l.u)-(f.y+f.u))/dx,worst=Math.abs(steep-b.m)>=Math.abs(shallow-b.m)?steep:shallow,wb=worst===steep?(f.y-f.u)-worst*f.x:(f.y+f.u)-worst*f.x,pad=60,xm=z=>pad+z/9*(w-pad-25),ym=z=>h-pad-z/(Math.max(...a.map(p=>p.y+p.u))*1.12)*(h-pad-45);a.forEach(p=>{const X=xm(p.x),Y=ym(p.y),U=Math.abs(ym(p.y+p.u)-Y);x.strokeStyle='#7695ae';x.beginPath();x.moveTo(X,Y-U);x.lineTo(X,Y+U);x.stroke();x.fillStyle='#57d3ff';x.beginPath();x.arc(X,Y,4,0,Math.PI*2);x.fill()});const L=(m,c,col)=>{x.strokeStyle=col;x.lineWidth=2;x.beginPath();x.moveTo(xm(0),ym(c));x.lineTo(xm(9),ym(m*9+c));x.stroke()};L(b.m,b.b,'#8ce99a');L(worst,wb,'#ffd166');q('#graphBenchSummary').innerHTML=`Best gradient <strong>${F(b.m,3)}</strong> · worst acceptable <strong>${F(worst,3)}</strong> · uncertainty <strong>${F(P(b.m-worst,b.m),2)}%</strong>`};
if(typeof renderCourse==='function')renderCourse();if(typeof renderTextbook==='function')renderTextbook();if(typeof renderFormula==='function')renderFormula();rows();rs();rc();dash();const ft=q('.footer');if(ft)ft.textContent='Educational teaching model aligned to AQA A-level Physics 7408 section 3.1 · Measurements & Errors Learning Lab v3.';
})();
